name = "rauda-ilm-app"
main = "backend/src/index.js"
compatibility_date = "2026-08-30"

[vars]
APP_NAME = "RAUDA ILM"

[[d1_databases]]
binding = "DB"
database_name = "rauda-ilm-db"
database_id = "d82a5615-e88a-49cf-90ab-1ec6c3bbdb3e"

[assets]
directory = "./frontend"
binding = "ASSETS"